graph LR
    A[r1] -- ether2 --> B[r2]
    A -- ether3 --> B
    A --> C["/tool ping"]
    A --> D["/tool traceroute"]
    A --> E["/tool torch"]
    A --> F["/tool netwatch"]
    C --> B
    D --> B
    E --> B
    F --> B
